### ISSUE TITLE
Create HomeScreen

### ISSUE THREAD

**Issue by Cybertron-Avneesh** [Cybertron-Avneesh/Silen-Shh#10]
Check below UIs for reference. Clicking on 3dots in right corner should work.
No need to implement cards shown in images.
![image](https://user-images.githubusercontent.com/54072374/94792321-6ff38300-03f6-11eb-9ea1-a3eadf6c5533.png)

![image](https://user-images.githubusercontent.com/54072374/94792369-81d52600-03f6-11eb-9add-0ed87a3a4497.png)

**Comment by singhalpranav22** [comment]
Why should we see wifi proximity for silenting as wifi dns network remain same for all the locations that particular wifi extender is that means in whole of the campus the phone would be silent. Should we mark some possible area on map and mute it in that area?

**Comment by cyber-venom003** [comment]
@Cybertron-Avneesh lemme handle this

**Comment by Cybertron-Avneesh** [comment]
> Why should we see wifi proximity for silenting as wifi dns network remain same for all the locations that particular wifi extender is that means in whole of the campus the phone would be silent. Should we mark some possible area on map and mute it in that area?

@singhalpranav22 most of the people will not enable their location. Also for this we need to have the exact location of user, and this will drain too much battery. Thats why I thought of using Wifi details.

**Comment by singhalpranav22** [comment]
@Cybertron-Avneesh Nice 👍
