### ISSUE TITLE
Design a Logo for App

### ISSUE THREAD

**Issue by Cybertron-Avneesh** [Cybertron-Avneesh/Silen-Shh#11]
I'm a passionate designer & I would love to do an app logo concept. Do assign me if u wish so.

_Originally posted by @itexpert2572000 in https://github.com/Cybertron-Avneesh/Silen-Shh/issues/4#issuecomment-701904869_

**Comment by Cybertron-Avneesh** [comment]
@itexpert2572000 you can start your work.

**Comment by Cybertron-Avneesh** [comment]
> @itexpert2572000 you can start your work.

Good work @itexpert2572000 👍

**Comment by akhil-tj** [comment]
Thanks for the opportunity @Cybertron-Avneesh
