### ISSUE TITLE
Add functionality to Send Feedback Button

### ISSUE THREAD

**Issue by Cybertron-Avneesh** [Cybertron-Avneesh/Silen-Shh#15]
The app should redirect to Gmail or a similar mailing app to Send feedback about the app.
Use email1234@email.com as the default email address of the receiver.

![image](https://user-images.githubusercontent.com/54072374/94892177-9e7a6800-04a1-11eb-9ad6-c86f41d74311.png)

**Comment by shobhit907** [comment]
Hey, could you assign this issue to me?

**Comment by Cybertron-Avneesh** [comment]
Yeah! Sure.
