### ISSUE TITLE
Add Functionality to Share button in Homescreen

### ISSUE THREAD

**Issue by Cybertron-Avneesh** [Cybertron-Avneesh/Silen-Shh#16]
Use https://github.com/Cybertron-Avneesh/Silen-Shh url and some relevent msg.
![image](https://user-images.githubusercontent.com/54072374/94892321-f4e7a680-04a1-11eb-891d-2f43ab07497b.png)

**Comment by ibrahimbroachwala** [comment]
I got this!

**Comment by Cybertron-Avneesh** [comment]
@ibrahimbroachwala Go ahead..
