### ISSUE TITLE
Add Floating Action Button in Homescreen

### ISSUE THREAD

**Issue by Cybertron-Avneesh** [Cybertron-Avneesh/Silen-Shh#17]
Tasks:
Add FAB in Homescreen.
On clicking which Homescreen will be overlayed with some color, and three more FABs will appear.
Refer to below image for better understanding. 
👍👍
![image](https://user-images.githubusercontent.com/54072374/94892492-64f62c80-04a2-11eb-8483-94b47eb12e65.png)

**Comment by goofy1916** [comment]
Hey, I can do this, please assign the task to me :)

**Comment by jhimly** [comment]
Have tried this issue out, please check
