### ISSUE TITLE
Add Splash screen

### ISSUE THREAD

**Issue by Cybertron-Avneesh** [Cybertron-Avneesh/Silen-Shh#3]
Take https://dlpng.com/png/6556225 logo for use (preferably in square shape), and add it to splash screen.

Attach Screenshot while creating a PR.

**Comment by Abhijeet-sonkar** [comment]
I would like to work on this issue

**Comment by Cybertron-Avneesh** [comment]
Go ahead @Abhijeet-sonkar

**Comment by NivasReddy21** [comment]
Can I work on this issue?
