### ISSUE TITLE
Add App Icon

### ISSUE THREAD

**Issue by Cybertron-Avneesh** [Cybertron-Avneesh/Silen-Shh#4]
As of now use https://dlpng.com/png/6556225  for logo.
We may change it later.

**Comment by DevanshCodes** [comment]
Can I work on this?

**Comment by akhil-tj** [comment]
I'm a passionate designer & I would love to do an app logo concept. Do assign me if u wish so.

**Comment by Cybertron-Avneesh** [comment]
@itexpert2572000 I will open a new issue for you and assign it to you. After designing a logo create a PR there. I think it will be okay for you. 

- design a logo preferably in square shape.
- logo should depict the concept  the of app. (read it from readme.md)

**Comment by Cybertron-Avneesh** [comment]
@DevanshCodes here you are supposed to add App Icon.

**Comment by DevanshCodes** [comment]
@Cybertron-Avneesh can you check it, I made the PR.

**Comment by Cybertron-Avneesh** [comment]
> @Cybertron-Avneesh can you check it, I made the PR.

please add a screenshot also.

**Comment by akhil-tj** [comment]
> @itexpert2572000 I will open a new issue for you and assign it to you. After designing a logo create a PR there. I think it will be okay for you.
> 
> * design a logo preferably in square shape.
> * logo should depict the concept  the of app. (read it from readme.md)

Eagerly waiting for assigning
